build:
    environment:
        php:
            version: 5.6

checks:
    php:
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_line_ending: true
        encourage_single_quotes: true

filter:
    excluded_paths:
        - test/*

tools:
    external_code_coverage: true
